"""
Django settings for HollCloud.

Generated by 'django-admin startproject'.

Configuración profesional para:
- Django REST Framework
- JWT Authentication
- Custom User Model (accounts.User)
- MySQL
- Variables de entorno con .env
"""

from pathlib import Path
import os

from dotenv import load_dotenv

# ------------------------------------------------------------------------------
# PATHS
# ------------------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde .env ubicado en la raíz del proyecto
load_dotenv(BASE_DIR / ".env")

# ------------------------------------------------------------------------------
# CORE SETTINGS
# ------------------------------------------------------------------------------

SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-change-this-in-production",
)

DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# ------------------------------------------------------------------------------
# APPLICATIONS
# ------------------------------------------------------------------------------

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS = [
    "rest_framework",
    "rest_framework_simplejwt",
]

LOCAL_APPS = [
    "apps.accounts.apps.AccountsConfig",
    "apps.chat",
    "apps.storage",
    "apps.workflows",
    "apps.notifications",
    "apps.audit",
    "apps.common",
    "apps.api",
    "rest_framework_simplejwt.token_blacklist",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# ------------------------------------------------------------------------------
# MIDDLEWARE
# ------------------------------------------------------------------------------

MIDDLEWARE = [
    "apps.common.middleware.TimingMiddleware",  # <-- Tu nuevo middleware
    "django_xbench.middleware.XBenchMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ------------------------------------------------------------------------------
# URLS / WSGI / ASGI
# ------------------------------------------------------------------------------

ROOT_URLCONF = "config.urls"

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# ------------------------------------------------------------------------------
# TEMPLATES
# ------------------------------------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ------------------------------------------------------------------------------
# DATABASE
# ------------------------------------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}

# ------------------------------------------------------------------------------
# CUSTOM USER MODEL
# ------------------------------------------------------------------------------

# En apps/accounts/models.py:
# class User(AbstractUser):
#     ...
AUTH_USER_MODEL = "accounts.User"

# ------------------------------------------------------------------------------
# PASSWORD VALIDATORS
# ------------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ------------------------------------------------------------------------------
# INTERNATIONALIZATION
# ------------------------------------------------------------------------------

LANGUAGE_CODE = "es-cl"
TIME_ZONE = "America/Santiago"

USE_I18N = True
USE_TZ = True

# ------------------------------------------------------------------------------
# STATIC AND MEDIA FILES
# ------------------------------------------------------------------------------

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",  # <-- Esto le dice a Django que busque en la carpeta 'static' de la raíz
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ------------------------------------------------------------------------------
# DEFAULT PRIMARY KEY
# ------------------------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ------------------------------------------------------------------------------
# DJANGO REST FRAMEWORK
# ------------------------------------------------------------------------------

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

# ------------------------------------------------------------------------------
# SIMPLE JWT
# ------------------------------------------------------------------------------

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# ------------------------------------------------------------------------------
# LOGGING
# ------------------------------------------------------------------------------


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'hollowcloud-cache',
        'TIMEOUT': 300,  # 5 minutos por defecto
        'OPTIONS': {
            'MAX_ENTRIES': 10000,  # Máximo de entradas en caché
        }
    }
}


# ------------------------------------------------------------------------------
# LOGGING
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
# LOGGING (Configuración completa)
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
# LOGGING (Configuración completa)
# ------------------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "DEBUG",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        # Logger para tu aplicación accounts (captura los logs de authenticate_user, etc.)
        "apps.accounts": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Logger para tu nuevo middleware de timing
        "apps.common": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Logger para errores internos de Django
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# ============================================================
# CONSTANTES DE CACHE Y RATE LIMITING
# ============================================================

# Cache negativa (usuarios que no existen)
CACHE_NEGATIVE_TTL = 300  # 5 minutos
CACHE_NEGATIVE_PREFIX = "user_not_found"

# Cache positiva (usuarios autenticados)
CACHE_POSITIVE_TTL = 3600  # 1 hora
CACHE_POSITIVE_PREFIX = "user_authenticated"

MAX_ATTEMPTS_IP = 10
MAX_ATTEMPTS_EMAIL = 5
RATE_LIMIT_WINDOW = 300  # 5 minutos
TIMING_ATTACK_SLEEP = 0.1  # 100ms


PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',     
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',     # Fallback
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher', # Fallback
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher', # Fallback
]

if DEBUG:
    # Reducir iteraciones para desarrollo (más rápido)
    from django.contrib.auth.hashers import Argon2PasswordHasher
    Argon2PasswordHasher.time_cost = 2  # Reducir de 3 a 2 (más rápido)
    Argon2PasswordHasher.memory_cost = 1024  # Reducir de 4096 a 1024 (menos memoria)
else:
    # En producción, mantener valores por defecto (seguros)
    pass