# Generated by Django 6.0.5 on 2026-05-19 02:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='storage.folder')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='chat.workspace')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='storage/')),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField()),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='storage.folder')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chat.workspace')),
            ],
            options={
                'verbose_name': 'Stored File',
                'verbose_name_plural': 'Stored Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='storage_versions/')),
                ('size', models.PositiveBigIntegerField()),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_versions', to=settings.AUTH_USER_MODEL)),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='storage.storedfile')),
            ],
            options={
                'verbose_name': 'File Version',
                'verbose_name_plural': 'File Versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='storage.storedfile')),
            ],
            options={
                'verbose_name': 'File Share',
                'verbose_name_plural': 'File Shares',
            },
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('workspace', 'parent', 'name'), name='unique_folder_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='fileversion',
            constraint=models.UniqueConstraint(fields=('stored_file', 'version_number'), name='unique_file_version_number'),
        ),
        migrations.AddConstraint(
            model_name='fileshare',
            constraint=models.UniqueConstraint(fields=('stored_file', 'shared_with'), name='unique_file_share'),
        ),
    ]
