# Generated by Django 5.2.7 on 2026-07-03 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de expiración de la invitación (7 días por defecto)', null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activo'), ('rejected', 'Rechazado')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['status'], name='chat_worksp_status_665a36_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['workspace', 'status'], name='chat_worksp_workspa_18778a_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['user', 'status'], name='chat_worksp_user_id_846ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['expires_at'], name='chat_worksp_expires_663dcc_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacemember',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('workspace', 'user'), name='unique_pending_invitation'),
        ),
    ]
