# Generated by Django 5.2.7 on 2026-07-03 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_workspacemember_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workspacemember',
            name='unique_pending_invitation',
        ),
    ]
